### ISSUE TITLE
Manufacturing Checklist

### ISSUE THREAD

**Issue by adamgreig** [cillian64/thegrid#16]
- [x] Make all serial cables
- [x] Make all power cables
- [x] Make all pole PCBs
- [x] Attach PCBs to LED strips

**Comment by cillian64** [comment]
- [x] make terminators
