### ISSUE TITLE
Software Checklist

### ISSUE THREAD

**Issue by adamgreig** [cillian64/thegrid#17]
* [ ] Updates to support RGB poles
* [ ] Work on CV
* [ ] Potential integration with apps/internet/etc
* [ ] Other improvements...

**Comment by cillian64** [comment]
- [ ] Updated leonardo control sink

**Comment by cillian64** [comment]
- [ ] android app / website for admin API control, eg changing patterns
 - [ ] gaming remote control from android or badge
